server: # REST server
  port: 8081
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    ws:
      port: 8080
      host: 0.0.0.0
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: true
      vimeo: false
      mixer: false
      http: false
      local: false
    sentryDsn: ""
    bufferDurationMs: 400
youtubePlaylistLoadLimit: 600
